language: ruby
rvm:
  - "2.0.0"
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/models/
before_script:
  - cp config/config.example.yml config/config.yml
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database livrodaclasse_test'
