#!/bin/bash

#######################
# Autor: Jorge Sallum #
# Data:  07/Out/2007  #
#######################

# TODO
# 0. #.#[A-Z]
# 1. Verificar: "A... ." e "a...".
# 2. Passar dicionário + sintaxe
# 3. Travessão --- e — (utf8)
# [^ ](
#filtrar erro "bla. santa Rosa"
#filtrar erro Masoch: parágrafo com minúscula, na 3030

esp='echo ..............................................................'

$esp
echo "Arquivos (num. de toques com cód. latex):"
for l in *tex; do
echo $l:`cat $l | wc -c` 
done
c='grep --color=auto -n '

$esp

echo "Digite o nome do arquivo (sem .\"tex\"), ou * para todos."
read i
i=$i.tex
echo Verificando $i....

$esp
echo "Erros possíveis? [y]"

read y
if [ $y = 'y' ]; then

$esp
echo "Códigos latex sem barra"
$c -e '[^\\]textit' $i
$c -e '[^\\]textsc' $i
$c -e '[^\\]section' $i
$c -e '[^\\]footnote' $i
$c "texsc"   $i
$c "texit"   $i

$esp
echo "dois pontos"
$c "\.\. "   $i

fi

$esp
echo "Verificar se aspas abrem e fecham? [y]"
read y
if [ $y = 'y' ]; then
$c -e "\“" -e "\”" -e "\`\`" -e "''" $i
fi

$esp
echo "Erros tipográficos: [y]"
read y
if [ $y = 'y' ]; then

$esp
echo "..."
$c -e \" -e "\.\.\." $i

$esp
echo "abrev. sem ~"
$c -e " p\. " -e " sr\. " -e " sra\. " $i
$c -e "Sr\. " -e " sra\. " -e " [A-Z]\. " $i

$esp
echo "footnote no começo da linha"
$c '^\\footnote' $i

$esp
echo "footnote sem espaço inicial"
$c -e 'footnote{[^ ]' $i

$esp
echo "ldots colado"
$c -e " \ldots" $i		#texto ...Palavra"

$esp
echo "ponto colado"
$c "\.[A-Z]" $i

$esp
echo "parêntese colado"
$c "[^{ ,~}](" $i		#parênteses colados
$c ")[^{ ,~,.,:,;,\\,\'}]" $i		#...)blabla

$esp
echo "hifem falso"
$c "­" $i

$esp
echo "códigos utf não aceitos"
$c "ª" $i

$esp
echo "espaço vírgula"
$c "\ ," $i 

$esp
echo "vírgula colada"
$c "\,[^\ ]" $i

$esp
echo "super-... anti-..."
$c -e "anti-[^hrs]" -e  "anti{}-[^hrs]" $i
$c -e "super-[^hr]" -e "super{}-[^hr]" $i

fi



#$esp
#echo "\`\`A (Maiúscula)...  blabla\.\'\' [y]"
#read y
#if [ $y = 'y' ]; then
rascunho="''"
#$c -e "\`\`[A-Z]" -e {\.,?,\!}$rascunho $i
#fi

$esp
echo "Números romanos e siglas sem versalete? [y]"
read y
if [ $y = 'y' ]; then
#  #I. #I# #I, 
num="I"
$c " $num\."," $num\,"," $num " $i
$c "II" $i
$c "IV" $i
num="V"
$c " $num\."," $num\,"," $num " $i
$c "VI" $i
$c "IX" $i
num="X"
$c " $num\."," $num\,"," $num " $i
$c "XI" $i
$c "XV" $i
$c "XX" $i
num="L"
$c " $num\."," $num\,"," $num " $i
$c "XL" $i
#Siglas
$c -e [A-Z][A-Z] $i 

fi

$esp
echo "Footnote: "
echo "1. possíveis notas dentro do ponto: (blabla}.) (olhar todos)" 
read y
if [ $y = 'y' ]; then
$c -e "}\." $i
fi

$esp
echo "Listar comentários? [y]"
read y
if [ $y = 'y' ]; then
$c % $i
fi

$esp
echo "Contextualizar palavras do dic.pws? [y]"
read y
if [ $y = 'y' ]; then
	sh dic.sh
fi

