restricted_area:
  username: "frodo"
  password: "shire"

development: &defaults
  latex_template_path: templates/
  books_path: /home/fellipe/tipografia-books/

test:
  <<: *defaults

sales:
  <<: *defaults

production:
  <<: *defaults

sletras:
  <<: *defaults

tipostaging:
  <<: *defaults
