defaults: &DEFAULTS
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *DEFAULTS
  database: livrodaclasse_development

test:
  <<: *DEFAULTS
  database: livrodaclasse_test

production:
  <<: *DEFAULTS
  database: livrodaclasse_production

tipostaging:
  <<: *DEFAULTS
  database: tipografia_staging
