require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CollaborationsController do

  # This should return the minimal set of attributes required to create a valid
  # Collaboration. As you add validations to Collaboration, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CollaborationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all collaborations as @collaborations" do
      collaboration = Collaboration.create! valid_attributes
      get :index, {}, valid_session
      assigns(:collaborations).should eq([collaboration])
    end
  end

  describe "GET show" do
    it "assigns the requested collaboration as @collaboration" do
      collaboration = Collaboration.create! valid_attributes
      get :show, {:id => collaboration.to_param}, valid_session
      assigns(:collaboration).should eq(collaboration)
    end
  end

  describe "GET new" do
    it "assigns a new collaboration as @collaboration" do
      get :new, {}, valid_session
      assigns(:collaboration).should be_a_new(Collaboration)
    end
  end

  describe "GET edit" do
    it "assigns the requested collaboration as @collaboration" do
      collaboration = Collaboration.create! valid_attributes
      get :edit, {:id => collaboration.to_param}, valid_session
      assigns(:collaboration).should eq(collaboration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Collaboration" do
        expect {
          post :create, {:collaboration => valid_attributes}, valid_session
        }.to change(Collaboration, :count).by(1)
      end

      it "assigns a newly created collaboration as @collaboration" do
        post :create, {:collaboration => valid_attributes}, valid_session
        assigns(:collaboration).should be_a(Collaboration)
        assigns(:collaboration).should be_persisted
      end

      it "redirects to the created collaboration" do
        post :create, {:collaboration => valid_attributes}, valid_session
        response.should redirect_to(Collaboration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved collaboration as @collaboration" do
        # Trigger the behavior that occurs when invalid params are submitted
        Collaboration.any_instance.stub(:save).and_return(false)
        post :create, {:collaboration => {  }}, valid_session
        assigns(:collaboration).should be_a_new(Collaboration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Collaboration.any_instance.stub(:save).and_return(false)
        post :create, {:collaboration => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested collaboration" do
        collaboration = Collaboration.create! valid_attributes
        # Assuming there are no other collaborations in the database, this
        # specifies that the Collaboration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Collaboration.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => collaboration.to_param, :collaboration => { "these" => "params" }}, valid_session
      end

      it "assigns the requested collaboration as @collaboration" do
        collaboration = Collaboration.create! valid_attributes
        put :update, {:id => collaboration.to_param, :collaboration => valid_attributes}, valid_session
        assigns(:collaboration).should eq(collaboration)
      end

      it "redirects to the collaboration" do
        collaboration = Collaboration.create! valid_attributes
        put :update, {:id => collaboration.to_param, :collaboration => valid_attributes}, valid_session
        response.should redirect_to(collaboration)
      end
    end

    describe "with invalid params" do
      it "assigns the collaboration as @collaboration" do
        collaboration = Collaboration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Collaboration.any_instance.stub(:save).and_return(false)
        put :update, {:id => collaboration.to_param, :collaboration => {  }}, valid_session
        assigns(:collaboration).should eq(collaboration)
      end

      it "re-renders the 'edit' template" do
        collaboration = Collaboration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Collaboration.any_instance.stub(:save).and_return(false)
        put :update, {:id => collaboration.to_param, :collaboration => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested collaboration" do
      collaboration = Collaboration.create! valid_attributes
      expect {
        delete :destroy, {:id => collaboration.to_param}, valid_session
      }.to change(Collaboration, :count).by(-1)
    end

    it "redirects to the collaborations list" do
      collaboration = Collaboration.create! valid_attributes
      delete :destroy, {:id => collaboration.to_param}, valid_session
      response.should redirect_to(collaborations_url)
    end
  end

end
