# -*- encoding : utf-8 -*-
development: &development
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: livrodaclasse_development
  pool: 5
  username: root
  password:


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: livrodaclasse_test
  pool: 5
  username: root
  password: